services:
  server:
    image: 12laboursnodejsapi:latest
    environment:
      API_PORT: ${API_PORT}
      PASSWORD_RESET_URL: ${PASSWORD_RESET_URL}
      USER_VERIFY_URL: ${USER_VERIFY_URL}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      API_KEY: ${API_KEY}
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_VERIFIED_SENDER: ${SENDGRID_VERIFIED_SENDER}
    ports:
      - "${API_PORT}:${API_PORT}"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  
  db:
    image: 12labourspostgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: