version: "3"

services:
  loginbackend:
    container_name: loginbackend
    # image: 12labours/nodejsapi-dev:60sexpire
    image: 12labours/nodejsapi-dev:latest
    environment:
      LOGIN_API_PORT: ${LOGIN_API_PORT}
      LOGIN_API_KEY: ${LOGIN_API_KEY}
      LOGIN_SECRET_KEY: ${LOGIN_SECRET_KEY}
      PASSWORD_RESET_URL: ${PASSWORD_RESET_URL}
      USER_VERIFY_URL: ${USER_VERIFY_URL}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_VERIFIED_SENDER: ${SENDGRID_VERIFIED_SENDER}
    ports:
      - "${LOGIN_API_PORT}:${LOGIN_API_PORT}"

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  postgresdb:
    container_name: postgresdb
    image: 12labours/postgres-dev:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
  pgadmin_data:
    driver: local
